### PR TITLE
Fixes rebirthes

### LINKED ISSUE #18: All Upgrades not resetting to 0 when rebirthing
When my friend was playing, he realised that after he rebirthed he would still get the same click power as before he rebirthed.

### PR DESCRIPTION
**Pull request by DangerChamp**
Fixes #18

### CODE REVIEW

**Review by donut28 — APPROVED** [review]
Looks good, thanks for helping!

**Comment by DangerChamp** [comment]
Acc dosen't work the multiplier line that I added broke some stuff

**Comment by donut28** [comment]
I have reverted the changes now so you can fix it

**Comment by donut28** [comment]
What stuff did it break?

**Pull request merged**
